name: Deploy to test Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH client
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client

      - name: Debug Environment Variables
        run: |
          echo "SSH_USER=${{ secrets.SSH_USER }}"
          echo "SSH_HOST=${{ secrets.SSH_HOST }}"

      - name: Deploy to Physical Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "$SSH_PRIVATE_KEY" > physical-server.pem
          chmod 600 physical-server.pem
          ssh -i physical-server.pem -o StrictHostKeyChecking=no "${SSH_USER}@${SSH_HOST}" "bash /home/ubuntu/myphp/deploy.sh"
